"""Remove column id from accestoken table

Revision ID: 1cf1abd04d5a
Revises: afe5aaa5a497
Create Date: 2025-08-14 21:09:22.838213

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1cf1abd04d5a"
down_revision: Union[str, Sequence[str], None] = "afe5aaa5a497"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("accesstoken", "id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "accesstoken", sa.Column("id", sa.INTEGER(), autoincrement=False, nullable=False)
    )
    # ### end Alembic commands ###
