"""Timed comment author in recipe

Revision ID: 57139488b4af
Revises: ea81012499a8
Create Date: 2025-08-10 12:04:32.711761

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "57139488b4af"
down_revision: Union[str, Sequence[str], None] = "ea81012499a8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("recipe_author_id_fkey"), "recipe", type_="foreignkey")
    op.drop_column("recipe", "author_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "recipe",
        sa.Column("author_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        op.f("recipe_author_id_fkey"), "recipe", "user", ["author_id"], ["id"]
    )
    # ### end Alembic commands ###
