"""Create FastAPI-Users table

Revision ID: 0fd3948ea10b
Revises: 542c5b5ba31b
Create Date: 2025-08-14 12:14:12.320014

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0fd3948ea10b"
down_revision: Union[str, Sequence[str], None] = "542c5b5ba31b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("hashed_password", sa.String(length=1024), nullable=False)
    )
    op.add_column("user", sa.Column("is_active", sa.Boolean(), nullable=False))
    op.add_column("user", sa.Column("is_superuser", sa.Boolean(), nullable=False))
    op.add_column("user", sa.Column("is_verified", sa.Boolean(), nullable=False))
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.drop_column("user", "username")
    op.drop_column("user", "password")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("password", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "user", sa.Column("username", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_column("user", "is_verified")
    op.drop_column("user", "is_superuser")
    op.drop_column("user", "is_active")
    op.drop_column("user", "hashed_password")
    # ### end Alembic commands ###
