"""Add many to many User && Recipes

Revision ID: 31f2763ed856
Revises: 1cf1abd04d5a
Create Date: 2025-08-15 11:48:29.822874

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "31f2763ed856"
down_revision: Union[str, Sequence[str], None] = "1cf1abd04d5a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("recipe", sa.Column("author_id", sa.Integer(), nullable=False))
    op.add_column("recipe", sa.Column("is_published", sa.Boolean(), nullable=False))
    op.create_foreign_key(None, "recipe", "user", ["author_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "recipe", type_="foreignkey")
    op.drop_column("recipe", "is_published")
    op.drop_column("recipe", "author_id")
    # ### end Alembic commands ###
